### ISSUE TITLE
Cucumber 2.0

### ISSUE THREAD

**Issue by zedtux** [cucumber/cucumber-rails#297]
The new cucumber has been release since weeks so it would be great to migrate now :-)

**Comment by mattwynne** [comment]
What exactly is the issue here? Is Cucumber-Rails incompatible with Cucumber 2.0?

**Comment by tom025** [comment]
I'm using cucumber-rails on a client project with cucumber 2.0. Working very well so far!

**Comment by zedtux** [comment]
Oops ... sorry .. I was expecting a kind of version 2 of cucumber-rails or announcement in the README ... sorry about that.

**Comment by Frost** [comment]
@zedtux @mattwynne @tom025: A new release of `cucumber-rails` is still needed, since the latest version available (as a github release and on rubygems) is [1.4.2](https://rubygems.org/gems/cucumber-rails), which was released on 2014-10-09, and that version has a dependency on `cucumber, < 2`.

The change to [allow cucumber 2](https://github.com/cucumber/cucumber-rails/commit/3165fdf4dcb4462cd5a32dfa9d9f12470bf6d716) (`cucumber, < 2.1`) was done on 2015-03-28.

**Comment by Kosmas** [comment]
@Frost that can be done in the very near future. 
There is a PR that is currently in progress, and when it's done we can have a new release.

**Comment by Frost** [comment]
@Kosmas Awesome stuff, thanks :)
