### ISSUE TITLE
Deprecation warning for '~@no-js-emulation' with cucumber 3.0.1

### ISSUE THREAD

**Issue by asartalo** [cucumber/cucumber-rails#346]
I'm getting the following when running with cucumber 3.0.1:

```
Deprecated: Found tagged hook with '~@no-js-emulation'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
```

**Comment by dbilek** [comment]
I have the similar issue:

`Deprecated: Found tags option '~@wip'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.`

**Comment by systemnate** [comment]
@dbilek - Is there anything in your `cucumber.yml` file that has `~@wip` in it?

**Comment by macfanatic** [comment]
Looks like #348 would solve this, not sure what the failures are looking through Travis though.

**Comment by bramski** [comment]
We also have:
```
Deprecated: Found tagged hook with '~@javascript'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Deprecated: Found tagged hook with '~@no-database-cleaner'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Deprecated: Found tagged hook with '~@no-database-cleaner'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
```

**Comment by bramski** [comment]
No such tags exist in our code base.

**Comment by kieuhua** [comment]
I also have the same issue. I wonder if the issue has been solved.
Thanks

**Comment by DannyBen** [comment]
Besides the point that there seems to be a bug somewhere, since a few people are getting these errors with no way of solving them - I for one think this change not an improvement. The old syntax was more succinct, and did not require putting this parameter in quotes, but I guess the authors had their reasons.

**Comment by bunnymatic** [comment]
I ran into this issue after some recent upgrades.

As it turns out, the tags are included in other gem's that I'm using.  To find the offenders, I went to my bundle directory and ran
`grep -l -r '~@wip` 
and got something like the following

```
...
./simplecov-0.15.0/cucumber.yml
./rspec-its-1.2.0/cucumber.yml
...
```
I was able to update some of the offenders to suppress this warning but some of the upgrade will be required by the gem owners (or by PR).

Hope this helps others figure out what's going on with their projects.

**Comment by DannyBen** [comment]
> As it turns out, the tags are included in other gem's that I'm using. 

Although it is a helpful comment, and this way we can find the culprit, I am still confused as to why cucumber complains about features of other gems (that are not even executed) when I am running feature tests for *my own* project. Seems like an overzealous deprecation case search on cucumber's part. The owners of those other gems should be the ones to see these warnings.

**Comment by triskweline** [comment]
`cucumber-rails` did define some hooks with the deprecated tag syntax (`~@tag` instead of `not @tag`).

This issue has been [fixed](https://github.com/cucumber/cucumber-rails/commit/edab35636702ef6b57f198242ea38f69d3c2c451) in `master`, but there hasn't been a new gem release in a while.

Can we get a new gem release?

**Comment by mvz** [comment]
@triskweline Unfortunately, the generate still includes the old tag syntax. Only the hooks in the step definitions were updated.

**Comment by triskweline** [comment]
@mvz Thanks for letting me know.

**Comment by xtrasimplicity** [comment]
The new release, v.1.6.0, will resolve this.
https://github.com/cucumber/cucumber-rails/issues/375

**Comment by LeonardoRomeo** [comment]
I have a similar problem, running my test cucumber throws a new exception like this:
"Found tagged hook with '~@javascript'.'~@tag' is no longer supported, use 'not @tag' instead. (RuntimeError)"
First problem was also with '~@wip', but i changed it in 'cucumber.yml with 'not @wip' and when i launch cucumber it doesn't matter anymore; I can't find  '~@javascript' anywhere, so i can't change it. Anyone knows where to find?

**Comment by mvz** [comment]
@LeonardoRomeo since this bug was fixed two years ago your problem is probably different (although the strikethrough makes it hard for me to figure out what your problem actually is). Can you open a new ticket please?
