### ISSUE TITLE
[cucumber-rails] Cut a release with Cucumber 4 support

### ISSUE THREAD

**Issue by JonRowe** [cucumber/cucumber-rails#470]
:wave: Hello, Cucumber 4 support was added to the repo ~ 5 months ago but has yet to be released, is it possible to get a release cut with this?

I've had success running cucumber 4 against the released `2.0.0`, so a `2.0.1` with just that version relaxed should be possible, I'd be happy to create a branch for just that relaxation if that would help...

**Comment by deivid-rodriguez** [comment]
A small correction is that although the commit that added cucumber 4 support was authored ~ 5 months, [it only landed last week](https://github.com/cucumber/cucumber-rails/pull/453).

In any case, I'd also be very happy with a release :)

**Comment by JonRowe** [comment]
My apologies, I've been running with a pre release version of cucumber 4 against the released version for a while, and only realised that the hard `< 4` was only preventing `4.0.0` this week and evidently didn't check the git history well enough!

**Comment by luke-hill** [comment]
Yes, so a brief history. Although perhaps not relevant now is.

At the time I pushed cucumber4 support, it failed. At this time we had a bug with rails 6.0.1 we weren't able to / didn't have time to triage.

Around 3 months ago, there were some changes in cucumber4 pre releases which seems to have either made this bug vanish, or maybe us using rails 6.0.2 and above fixed it (I'm not sure again).

Around 1 month ago the official cucumber4 cut was made, and since then everything "seems" ok. I'll promise to dedicate a bit more time to this, but unfortunately RL has screwed me over a bit (Trapped in another country losing job e.t.c.). But I'm a bit more stable now. So we should be releasing 1 or more cuts of this gem soon.

**Comment by deivid-rodriguez** [comment]
@luke-hill I'm glad you're doing better now.

**Comment by acunskis** [comment]
Looks like actual gem for 2.1.0 did not end up in rubygems

**Comment by luke-hill** [comment]
Be patient. It will. We have a methodology that I had to reset and wait a few days for.

**Comment by luke-hill** [comment]
Release cut on rubygems :) Closing issue

**Comment by JonRowe** [comment]
Thanks!
